name: 'Update the list of my liked repositories'
on:
  schedule:
    -
      cron: '30 18 * * *'
  workflow_dispatch:
  hello world I Am Boy github
  
jobs:
  build:
    name: 'stargazed'
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Use GitHub Actions'
        uses: actions/checkout@v2
      -
        name: 'Use Node.js 12.x'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      -
        name: 'Install Package'
        run: 'npm install --global stargazed'
      -
        name: 'Update Repo'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: 'stargazed --username  "maxgfr" --token ${GITHUB_TOKEN} --repo "awesome-stars" --message "update readme.md" --sort'
